//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoEyeCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYL
    {
        public long Id { get; set; }
        public string CYL1 { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
