//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoEyeCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_configuration
    {
        public int id { get; set; }
        public string type { get; set; }
        public string type_display { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
