//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoEyeCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactLenses
    {
        public long Id { get; set; }
        public string customerId { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string mobno { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string orderDate { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveredOn { get; set; }
        public string RefNo { get; set; }
        public string Examinedy { get; set; }
        public string rightDistanceSPH { get; set; }
        public string rightDistanceCYL { get; set; }
        public string rightDistanceAxis { get; set; }
        public string rightAddition { get; set; }
        public string rightPD { get; set; }
        public string leftDistanceSPH { get; set; }
        public string leftDistanceCYL { get; set; }
        public string leftDistanceAxis { get; set; }
        public string leftAddition { get; set; }
        public string leftPD { get; set; }
        public Nullable<decimal> totalPayment { get; set; }
        public Nullable<decimal> advancedPayment { get; set; }
        public Nullable<decimal> BalancePayment { get; set; }
        public Nullable<int> frame { get; set; }
        public Nullable<int> lenses { get; set; }
        public string remarks { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updtedDate { get; set; }
        public Nullable<bool> flag { get; set; }
        public string entryType { get; set; }
        public string vision { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public string leftvision { get; set; }
    }
}
